### ISSUE TITLE
Write data timestamps based on data in the check files

### ISSUE THREAD

**Issue by timarney** [cds-snc/security-goals#105]
@maxneuvians can you provide a sample check file for this and then we can fill in the rest of the details for this issue.

**Comment by maxneuvians** [comment]
```
{"origin":"gcr.io/security-goals/checks/url-exists","timestamp":"2019-05-15T16:30:32Z","satisfies":["SA-11","SA-11 (1)"],"passed":true,"description":"The application uses an ESLint file to do static code analysis.","references":"https://github.com/cds-snc/cra-alpha/blob/master/.eslintrc.json","component":"Source code","release":"RELEASE_ID"}
```

where RELEASE_ID is either `ABCD-1234` or `1234`. `1234` is the timestamp we need to use.

**Comment by timarney** [comment]
@brdunfield thinking we should add a new database column for this maybe processedAt or something.  That way Mongo still uses the built in created at + updated for later reference.

To do this we'll need the logic to write the data updated + updated model.ts in the db dir.

After we have the column and data in place we'll need to update the database queries to sort using that column.

**Comment by brdunfield** [comment]
When the RELEASE_ID is in this format: "60e61288-ef33-11e8-908e-06d86cf01138" how do I extract a date from this? @maxneuvians

**Comment by timarney** [comment]
Ignore that format - likely old files.

You can grab some check here [prod-checks.zip](https://github.com/cds-snc/security-goals/files/3259331/prod-checks.zip)
