### ISSUE TITLE
Local version of web-report does not match deployed version

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/security-goals#106]
For example:
Local version of web-report contains a "Print this Page" button.
Deployed version does not.

**Comment by maxneuvians** [comment]
PDF reports are in an undocumented feature flag - so two things we need to so. You can see it working in the PR reviews here: https://github.com/cds-snc/security-goals/blob/master/review-manifests/web-report-deployment.yaml#L33-L34

- [ ] Add `PDF_REPORT_URL`  in security-goals-demo repo: https://github.com/cds-snc/security-goals-demo/blob/master/manifests/base/web-report-deployment.yaml
- [ ] Document it

**Comment by timarney** [comment]
Given we have that `PDF_REPORT_URL` defined in the .env.example file thinking that's enough to cover off this issue ("does not match deployed version")

The main repo Readme mentions it and also says `web-report` etc.. is not fully documented.  We can open up new issues for those as need be.
