### ISSUE TITLE
Runner will hang on occasion and lock itself. 

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/security-goals#116]
`"(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

**Comment by timarney** [comment]
@maxneuvians still happening?

**Comment by timarney** [comment]
Will re-open as need be.
