### ISSUE TITLE
When using the Web Report I need the page to be available in french so that I can say I meet the official language act

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/security-goals#133]
AC:
- French Language toggle in Web report UI that changes the words in the UI
- Does not change the controls written languages

To translate (e.g)
- Are we meeting our security goals?
- Print this page (PDF)
- Latest Releases:
- Failed Release
- Passed Release
- Checks
- Back to top of page
- Date/Time
- Some checks have failed
- 10 of 13 passing
- Back to home

**Comment by timarney** [comment]
Going to start the setup for this using React Context.

**Comment by timarney** [comment]
Setup is in place for this now - next steps add the translations.

**Comment by timarney** [comment]
@willeybryan this can be picked up for translation now 

Here's the file.
https://github.com/cds-snc/security-goals/blob/master/web-report/src/i18n/translations.json

**Comment by timarney** [comment]
Going to close this as the the pieces are in place / merged.
