### ISSUE TITLE
Set the name of reports through ENV variables

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/security-goals#140]
We should be able to define the name of the app we are running compliance against with an ENV variable. For example the PDF report has a hard coded `CRA Alpha` in it. This needs to be dynamic. 

This name should show up in all the apps if needed.

**Comment by maxneuvians** [comment]
Did PDF Report in #143

**Comment by timarney** [comment]
As in where is says 

> "Are we meeting our security goals?"
