### ISSUE TITLE
When viewing the Web-report I need a way to get to the performance index and back again without having to edit the URL

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/security-goals#150]
Acceptance Criteria
- Next to Print this Page (PDF) place a link toe the Performance Index 
- Make it the same Style as the other links
- Move the toggle for French to the right side of the page (To the left of the CDS logo)
- Put a link in the same spot on the Performance index page that says Web Report

**Comment by willeybryan** [comment]
![image](https://user-images.githubusercontent.com/46505127/59374675-68e4c500-8d1a-11e9-9248-9eb1a79c38ce.png)

**Comment by willeybryan** [comment]
![image](https://user-images.githubusercontent.com/46505127/59374719-79953b00-8d1a-11e9-815d-733891250eff.png)

**Comment by timarney** [comment]
This is done on the Web Report end.

**Comment by timarney** [comment]
Just merged PR for Performance index -> Web Report.

Note:  These will only show if the .env variables are set.
