### ISSUE TITLE
email support in notifier

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/security-goals#66]
The notifier needs to support downloading the latest report and sending it via email to recipients specified in the env file.

**Comment by willeybryan** [comment]
We will also need a way for the user who received the emails to 'unsubscribe'
1) Method for them to unsubscribe
2) Logs that they have

Not a Priority atm but if we are going to get people outside CDS to use it this is a must.

**Comment by willeybryan** [comment]
Also should we actually send the file or a link to the Report/file?

**Comment by maxneuvians** [comment]
Send file, we want it to be archived with them

**Comment by timarney** [comment]
@maxneuvians 

Going to add a JWT (https://jwt.io/) to protect this but I have a prototype up and running on AWS Lamda now.  Allows you to set the recipient via a environment variable + set the message and add an attachment.  

<img width="967" alt="Screen Shot 2019-06-03 at 1 40 57 PM" src="https://user-images.githubusercontent.com/62242/58822426-7658cb80-8605-11e9-8d91-c898d62506eb.png">

**Comment by timarney** [comment]
Email Notifier is setup as a standalone repo here https://github.com/cds-snc/email-notify it's functional at this point so going to close this issue.

We'll likely need to make adjustments in AWS for verified domains etc... but those can be tracked separately.

The Readme in the other repo covers the setup and @maxneuvians has the token I'm using for JWT auth.
