### ISSUE TITLE
API misses check files when it is currently ingressing a queue

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/security-goals#67]
It looks like certain check files are not ingressed if they arrive in the checks directory while another batch of checks is being ingressed

**Comment by timarney** [comment]
Going to swap the watch code to use https://github.com/paulmillr/chokidar - which seems to have better support at this point vs "watchr"

That said seeing some issues noted i.e. https://github.com/paulmillr/chokidar/issues/849 issues with memory when watching a "large" amount of files 

> "34k files to a watched directory, the nodejs process takes over 3GB of memory"

We'll cross that bridge if / when we come it.  Maybe look at something outside of Node for the watching as needed.

**Comment by willeybryan** [comment]
From the Trello Card:

Current Bug:
- Watches a directory, watches the files, puts them into a queue to process them. 
- If another files gets inserted into the directory it doesn't get checked.
- Node concurrency issue

Acceptance Criteria
- Refactor API to support pushes while checking and don't miss any files.

**Comment by timarney** [comment]
PR is merged.

@maxneuvians is going to test on the server.

**Comment by timarney** [comment]
Closing this - can re-open if the issue resurfaces.
