### ISSUE TITLE
When looking for specific controls I want a search/Filter box so I can type the information I have so I don't have to look through everything.

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/security-goals#90]
- [x] Add Date range selector at the top of the page under the header but before results
- [x] Filter results to that page
- [x] Little X to clear the box
- [ ] Test for accessibility

**Why?**
- There is a huge history of controls being checked over time that we can't expect a user to read through

**Comment by timarney** [comment]
Note: I'm working on code for the api end of this.

**Comment by timarney** [comment]
See: https://github.com/cds-snc/security-goals/pull/136 for date range queries
