### ISSUE TITLE
When comparing releases with failed controls I want to see the performance index tied to a release as not controls are created equal.

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/security-goals#94]
**Acceptance Criteria**
- Performance index should be available in a UI on each release
- Performance index should show in the release-box div as a percent on the Web report home page
- Performance index should show in the actual release in the status-bar div? or give it it's own bar under the status bar. (Stretch Goal, can happen later)
- Performance index should be colour coded (<5% risk, Green. <30% risk yellow, <50% orange, <100% Red)
- Performance index should be based on values from https://github.com/cds-snc/security-goals/issues/93 (currently default of 1, weighting all controls equally)

**Why?**
- I can glance at releases in the list I should be able to see which ones bring the most Performance to the product. In the future when we change the weighting of the controls it will bring more relevance, as for now, 9/10 controls will show 90% Performance which we accept as dumb, for now.

**Comment by maxneuvians** [comment]
Making some headway with this on #110
