### ISSUE TITLE
When viewing performance of controls I want the Performance index to be a weighted average so that we can gather feedback on the system.

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/security-goals#95]
**Acceptance Criteria**
- Controls all have a value of 1 for risk and a weight of 1 for risk. Other values may be added later. 
- To calculate risk value for a release calculate a weighted average

**Why?**
- if we test with users and it shows 9/10 controls passed Risk 10% that will illicit a user focus on that.
- We can make up arbitrary weights to the controls for testing purposes.

**Future**
- Probably something using the Thomas scoring system with an evaluation system like Acceptance Criteria
- Summarize rules into a performance index
- see https://evaluator.severski.net/articles/usage.html#summarize-results

**Comment by maxneuvians** [comment]
Making some headway with this on #110

**Comment by maxneuvians** [comment]
Closed in #110
