### ISSUE TITLE
When writing rules developers need a guide on how to write effective rules that actually index risk so that the tool can be used effectively

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/security-goals#96]
**Acceptance Criteria**
- Boring Documentation
- Probably in Github
- Include examples
- Prototype documentation audience is developers

**Why?**
- Developers will need to write the rules for their projects
- Examples and documentation is needed for them to do this
- We want to have this so we can go get developers at CDS to try this and provide feedback on why it did or didn't work for them.

**Future**
- Developers writing their own rules creates a barrier to entry. We want to reduce this as much as possible.
- If it is possible for use to supply the rules then the audience should be CDS devs and we can look to provide general rules for everyone later.

**Comment by timarney** [comment]
Wondering if a starting point on this would be to see if we can define what if any rules could be portable between projects.  If we can do that maybe that can act as a starting guide that we can write docs around.  

If we can't define X # of rules that are portable  .... ??

**Comment by timarney** [comment]
I'm going to start by writing a tutorial on how to create check.

"Ensuring secret scanning is part of your CI pipeline"

https://github.com/cds-snc/security-goals-demo/blob/master/manifests/checks/ia-5-7.yaml

Using this particular check should keep the conversation focused avoiding the "I wouldn't consider this a valid check for i.e. static code analysis" debate conversation.

**Comment by timarney** [comment]
First go https://github.com/cds-snc/security-goals/blob/writing-a-check/docs/writing-a-check.md
