### ISSUE TITLE
When using the tool there will be configuration settings that users need to manage. They will need a UI to do that in as not all users are developers that can modify code.

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/security-goals#97]
**Acceptance Criteria**
- In the header next to the CDS logo can we through a cog :gear: icon that leads users to a new settings page
- Settings page is just Max's Performance index page for now
- Use the existing page frame work to keep page accessible 

**Why?**
- We are going to need to add settings for users to configure to adjust the tools. We can't rely on them adjusting environment variables as it is a sub optimal UX and provides a barrier to usage. 

**Future**
- Probably want a Setting the values on rules
- Probably want to configure who gets notifications and reports.

**Comment by timarney** [comment]
Anyone have thoughts on what an end user would need to configure via a UI outside email recipient?

Thinking perhaps this will be more in need "way" down the road vs now.

**Comment by willeybryan** [comment]
- Manual/Custom Rules 
- Policy and Process locations
- Rule weights and TSS factors
- User permissions

**Comment by timarney** [comment]
IMO - we should hold on this until after more user research is done.

As it stands from my vantage point:
- Rules for now need to be handled by a developer
- weights and TSS factors is in flux until further conversation
- user permission (we don't have a login system yet)

Hard to tell at this point given the unknowns what a settings panel should look like outside of a bunch of input fields.

Also we need to discuss where we want to save the values once we know what we want to save i.e. central database managed by CDS?

**Comment by willeybryan** [comment]
That is fair, we will wait until we have conducted some research.

Closing as won't do.
