### ISSUE TITLE
Remove sorting logic from Details Page component

### ISSUE THREAD

**Issue by timarney** [cds-snc/security-goals#98]
Now that https://github.com/cds-snc/security-goals/pull/92 is merged we should be able simplify the Details Page component (web report).  No need to do the sorting for pass, fails in the UI now.

The query can be updated to give us back passes and fails in an array i.e.
```
query {
  passing: releases(releaseType: PASSING) {
    _id
    release
    passed
...other fields ....
  }
  failing: releases(releaseType: FAILING) {
    _id
    passed
   ...other fields ....
  }
}
```

<img width="604" alt="Screen Shot 2019-05-30 at 3 19 35 PM" src="https://user-images.githubusercontent.com/62242/58658658-f70a8580-82ee-11e9-9ad1-59447c089090.png">
<img width="259" alt="Screen Shot 2019-05-30 at 3 23 20 PM" src="https://user-images.githubusercontent.com/62242/58658667-fc67d000-82ee-11e9-909f-9e584b37d428.png">

**Comment by maxneuvians** [comment]
@timarney this is the query that we need to succeed:

```
query{controlReleases(id:"RA-5"){
  releases(releaseType: PASSING) {
    _id
    release
    timestamp
    passed
    passing
    total
    controls {
      control
      fileId
      verifications {
        origin
        timestamp
        passed
        description
        release
        component
        references
      }
    }
  }}}
```

**Comment by timarney** [comment]
Can try using this now.  Seems to work with my small set of sample data.
```
query{controlReleases(id:"RA-5", releaseType: PASSING){
  releases {
    _id
    release
    timestamp
    passed
    passing
    total
    controls {
      control
      fileId
      verifications {
        origin
        timestamp
        passed
        description
        release
        component
        references
      }
    }
  }}}
```
